site_name: digest
site_url: https://github.com/eddelbuettel/digest
docs_dir: src
site_dir: docs
copyright: Copyright &copy; 2003 - present Dirk Eddelbuettel
repo_url: https://github.com/eddelbuettel/digest
edit_uri: ""

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
  font:
    text: Lato
  favicon: assets/Rlogo.png
  logo: assets/Rlogo.svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eddelbuettel/digest
      name: digest on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eddelbuettel
      name: eddelbuettel on Twitter

#plugins:
#  - social
     
nav:
  - Home:
    - index.md
  - Reference:
    - man/digest.md
    - man/AES.md
    - man/digest2int.md
    - man/hmac.md
    - man/makeRaw.md
    - man/sha1.md
    - man/vdigest.md
  - Articles:
    - Sha1 Vignette: vignette.md
  # - News:
  #   - news.md
  - Changelog:
    - changelog.md
